services:
  calculator:
    build: .
    container_name: calculator_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    mem_limit: 256m

  redis:
    image: redis:7
    container_name: redis_db
    mem_limit: 128m

